### ISSUE TITLE
Clone of terkel.com?

### ISSUE THREAD

**Issue by pyramidium** [mkurk/kurk.io#1]
I'm pretty sure you ripped this site from here https://github.com/terkelg/terkel.com-2016

**Comment by mkurk** [comment]
I cloned his repo as it was literally the most 🔥🔥vue.js template that I
have seen.

Moving forward I will do the following:

1) give credit via link in my current site
2)delete the website and visit my local priest for a consultation
3) donate an agreed sum of money to the  owner of the source code
